alter session set "_ORACLE_SCRIPT"=true;

CREATE TABLE PROVEEDOR(
    ID_PROVEEDOR NUMBER PRIMARY KEY,
    RAZON_SOCIAL VARCHAR2(260) NOT NULL UNIQUE,
    RUC CHAR(11) NOT NULL UNIQUE,
    ESTADO CHAR(1) DEFAULT '1'
);

CREATE SEQUENCE SEQ_PROVEEDOR;

INSERT INTO PROVEEDOR(ID_PROVEEDOR,RAZON_SOCIAL,RUC) 
VALUES(SEQ_PROVEEDOR.NEXTVAL,'Productos Amazonences','2054987254');

INSERT INTO PROVEEDOR(ID_PROVEEDOR,RAZON_SOCIAL,RUC) 
VALUES(SEQ_PROVEEDOR.NEXTVAL,'Inversiones la Cruz','1054987200');

INSERT INTO PROVEEDOR(ID_PROVEEDOR,RAZON_SOCIAL,RUC) 
VALUES(SEQ_PROVEEDOR.NEXTVAL,'Inversiones Nueva Alegria','2054987200');

COMMIT;

-- SELECT * FROM PROVEEDOR;

SELECT ID_PROVEEDOR,RAZON_SOCIAL,RUC,ESTADO FROM PROVEEDOR;


select SEQ_PROVEEDOR.NEXTVAL from dual;

UPDATE PROVEEDOR SET  RAZON_SOCIAL='Hermanos Novoa1',RUC='20544887824' WHERE ID_PROVEEDOR=7;

DELETE FROM PROVEEDOR WHERE ID_PROVEEDOR=7;
